# Generated by Django 2.2.1 on 2019-05-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videostatistics',
            old_name='calification',
            new_name='sumCalification',
        ),
        migrations.AddField(
            model_name='videostatistics',
            name='calicationsCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
